### ISSUE TITLE
Multi-user capabilities

### ISSUE THREAD

**Issue by theFork** [haggl/dotmgr#2]
When creating links for other users - say root - what would be an appropriate procedure? Will running the script as root work? Or would it make sense to add some kind as user-tags? Or a comment in the first line of each dotfile indicating the target users?

**Comment by haggl** [comment]
I see no reason why running the script as root would NOT work.

Haven't tested it yet though!

On October 25, 2016 8:24:21 AM CEST, Simon Gansen <notifications@github.com> wrote:
>When creating links for other users - say root - what would be an
>appropriate procedure? Will running the script as root work? Or would
>it make sense to add some kind as user-tags? Or a comment in the first
>line of each dotfile indicating the target users?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/haggl/dotmgr/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by haggl** [comment]
See also: #9
